version: '3.8'

services:
  # New York City Region
  lis-nyc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lis-nyc
    hostname: lis-nyc
    privileged: true  # Required for FUSE and tc networking
    environment:
      - LIS_REGION=NYC
      - LIS_NODE_ID=nyc-1
      - LIS_CLUSTER=lis-mvp-cluster
      - LIS_BIND_ADDR=0.0.0.0:7001
      - LIS_PEER_ADDRS=lis-london:7002,lis-tokyo:7003
      - RUST_LOG=info
    volumes:
      - /tmp/lis-nyc:/mnt/lis:shared
      - ./demo:/demo:ro
    ports:
      - "8001:8000"  # Optional S3 API port
      - "7001:7001"  # RHC peer port
    networks:
      - lis-global
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    command: >
      sh -c "
        echo 'Setting up NYC network latency simulation...' &&
        /demo/setup-latency.sh nyc &&
        echo 'Starting Lis mount...' &&
        mkdir -p /mnt/lis &&
        /app/target/release/lismount lis-mvp-cluster:/ /mnt/lis
      "

  # London Region  
  lis-london:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lis-london
    hostname: lis-london
    privileged: true
    environment:
      - LIS_REGION=LONDON
      - LIS_NODE_ID=lon-1
      - LIS_CLUSTER=lis-mvp-cluster
      - LIS_BIND_ADDR=0.0.0.0:7002
      - LIS_PEER_ADDRS=lis-nyc:7001,lis-tokyo:7003
      - RUST_LOG=info
    volumes:
      - /tmp/lis-london:/mnt/lis:shared
      - ./demo:/demo:ro
    ports:
      - "8002:8000"
      - "7002:7002"
    networks:
      - lis-global
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    command: >
      sh -c "
        echo 'Setting up London network latency simulation...' &&
        /demo/setup-latency.sh london &&
        echo 'Starting Lis mount...' &&
        mkdir -p /mnt/lis &&
        /app/target/release/lismount lis-mvp-cluster:/ /mnt/lis
      "

  # Tokyo Region
  lis-tokyo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lis-tokyo
    hostname: lis-tokyo
    privileged: true
    environment:
      - LIS_REGION=TOKYO
      - LIS_NODE_ID=tok-1
      - LIS_CLUSTER=lis-mvp-cluster
      - LIS_BIND_ADDR=0.0.0.0:7003
      - LIS_PEER_ADDRS=lis-nyc:7001,lis-london:7002
      - RUST_LOG=info
    volumes:
      - /tmp/lis-tokyo:/mnt/lis:shared
      - ./demo:/demo:ro
    ports:
      - "8003:8000"
      - "7003:7003"
    networks:
      - lis-global
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    command: >
      sh -c "
        echo 'Setting up Tokyo network latency simulation...' &&
        /demo/setup-latency.sh tokyo &&
        echo 'Starting Lis mount...' &&
        mkdir -p /mnt/lis &&
        /app/target/release/lismount lis-mvp-cluster:/ /mnt/lis
      "

networks:
  lis-global:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16